### ISSUE TITLE
Problem Adding Location

### ISSUE THREAD

**Issue by BrownCoatSGT** [fuel9/DisplayMonkey#137]
When I try to add a new location using longitude and latitude, I receive the below error.
The remote name could not be resolved: 'query.yahooapis.com'
at DisplayMonkey.Controllers.LocationController.GetDefaultWoeid(Nullable`1 latitude, Nullable`1 longitude)
   at DisplayMonkey.Controllers.LocationController.Edit(Location location)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)

**Comment by psined1** [comment]
Logging as a possible bug

**Comment by Gumbees** [comment]
@DisplayMonkey any news on this? We're new users on a blank install experiencing the same issue. We'd like to use this in production. Will pay bounty for bug fix.

**Comment by HansKatsman** [comment]
the problem is when you add the latitude and longitude immediately. The woeid is not on this screen but is required.
**Solution is to leave the lat and long empty while creating the new location.**
Then edit the location and now it's possible to enter the Lat and Long data and a value for WOEID because the field is visible. I enter just 1 in case I do not know
