### ISSUE TITLE
dm in subfolder possible?

### ISSUE THREAD

**Issue by wvt-adm** [fuel9/DisplayMonkey#166]
good morning everybody - i would like to set up displaymonkey in a subfolder in iis. domain.tld/subfolder/dm and domain.tld/subfolder/dmm unfortunately it doesn't seem to work just like that. do you have an idea what exactly i'm doing wrong? and yes - if i leave out the subfolder it works... with subfolder i get the following error message: 
--------------------------
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'displayId'. 
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) 
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) 
 at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() 
 at System.Data.SqlClient.SqlDataReader.get_MetaData() 
 at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) 
 at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) 
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) 
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) 
 at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) 
 at System.Data.SqlClient.SqlCommand.ExecuteReader() 
 at DisplayMonkey.DataAccess.<>c__DisplayClass7_0.<ExecuteReaderExt>b__0() 
 at DisplayMonkey.DataAccess.ConnectionWrap(SqlCommand cmd, Action action) 
 at DisplayMonkey.Display..ctor(Int32 displayId) 
 at DisplayMonkey.Canvas.InitFromDisplay(Int32 displayId) 
 at DisplayMonkey.getCanvas.Page_Load(Object sender, EventArgs e) 
ClientConnectionId:d9b660b1-1772-4256-8a78-78f5923dac7e 
Error Number:207,State:1,Class:16 
---------------------------
thank you very much for your help in advance - best regards on

Translated with www.DeepL.com/Translator (free version)

**Comment by michaelmalmgren** [comment]
Where in DM are you when you receive this error?

**Comment by michaelmalmgren** [comment]
You may have to set the path to the presentation application. See the setting "Presentation site URL" under Setup – Other – Application Settings

You can read about it here: http://www.displaymonkey.org/dm/documentation/application-settings/

**Comment by wvt-adm** [comment]
good morning, yes of course – this i have setup -> i have try this

http://www.domain.tld/place/displaymonkey/
http://www.domain.tld/place/displaymonkey
http://www.domain.tld/place/
http://www.domain.tld/place

but with all this settings i receive on the -> http://www.domain.tld/place/displaymonkey

after i register the display this error: -> the register page shows correctly

System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'displayId'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader()
at DisplayMonkey.DataAccess.<>c__DisplayClass7_0.<ExecuteReaderExt>b__0()
at DisplayMonkey.DataAccess.ConnectionWrap(SqlCommand cmd, Action action)
at DisplayMonkey.Display..ctor(Int32 displayId)
at DisplayMonkey.Canvas.InitFromDisplay(Int32 displayId)
at DisplayMonkey.getCanvas.Page_Load(Object sender, EventArgs e)
ClientConnectionId:e3219525-84b9-4225-a2b5-6b968964d4e5
Error Number:207,State:1,Class:16

have you an idea what i make wrong?

second question – whats the costs of payd support?

thanks a lot and best regards

am



Von: Michael Malmgren [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. Februar 2020 09:06
An: fuel9/DisplayMonkey <DisplayMonkey@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [fuel9/DisplayMonkey] dm in subfolder possible? (#166)


You may have to set the path to the presentation application. See the setting "Presentation site URL" under Setup – Other – Application Settings

You can read about it here: http://www.displaymonkey.org/dm/documentation/application-settings/

**Comment by michaelmalmgren** [comment]
What is your path to the management application?

**Comment by wvt-adm** [comment]
the display is -> http://www.domain.tld/place/dm
and the management is -> http://www.domain.tld/place/dmm

;-) – thanks for your help

Von: Michael Malmgren [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. Februar 2020 19:17
An: fuel9/DisplayMonkey <DisplayMonkey@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [fuel9/DisplayMonkey] dm in subfolder possible? (#166)


What is your path to the management application?

**Comment by michaelmalmgren** [comment]
Hi, when you say "after i register the display" - where exactly are you in the application? Maybe you can add some screenshot showing the steps you are taking.
