### ISSUE TITLE
Problem with Configurations

### ISSUE THREAD

**Issue by robertocastroserantes** [fuel9/DisplayMonkey#4]
Hello, when I want to change any numeric option in Setup-->Other-->Configurations like **Caché Expiration,Max image upload size...** I receive an error. In this case, this is the error when I want to increase the maximum image upload size:

Source -- Setting/Edit
Message -- Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

StackTrace

   at System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component)
   at System.Web.Mvc.AssociatedMetadataProvider.<>c__DisplayClass3.<GetPropertyValueAccessor>b__2()
   at System.Web.Mvc.ModelMetadata.get_Model()
   at System.Web.Mvc.DataAnnotationsModelValidator.Validate(Object container)
   at System.Web.Mvc.ModelValidator.CompositeModelValidator.<Validate>d__1.MoveNext()
   at System.Web.Mvc.DefaultModelBinder.OnModelUpdated(ControllerContext controllerContext, ModelBindingContext bindingContext)
   at System.Web.Mvc.DefaultModelBinder.BindComplexElementalModel(ControllerContext controllerContext, ModelBindingContext bindingContext, Object model)
   at System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
   at System.Web.Mvc.DefaultModelBinder.BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19

Thank you.

**Comment by DisplayMonkey** [comment]
This was fixed in 1.3.1
