### ISSUE TITLE
"Visualization URL" error with Power BI frames

### ISSUE THREAD

**Issue by janicedawley** [fuel9/DisplayMonkey#70]
We just recently started receiving the following error when added/editing Power BI frames. We haven't changed anything on our end (still DisplayMonkey v.1.6.0.182), and this was working as recently as a couple of weeks ago. Any ideas on what's happening?

An error occurred while processing your request.

Source | Powerbi/Edit

Message | The field Visualization URL must be a string or array type with a maximum length of '200'.

The full stack trace is:

   at DisplayMonkey.Models.DisplayMonkeyEntities.SaveChanges()
   at DisplayMonkey.Controllers.PowerbiController.Edit(Powerbi powerbi)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by moeman2323** [comment]
I am just setting up Display Monkey to test PowerBI on it and ran into the same issue. Have you found a solution for this? 

Thanks,

Mike

**Comment by janicedawley** [comment]
I haven't. I frankly have no clue where to look. I'm guessing Microsoft changed something on their end, and DisplayMonkey needs to be updated to be compatible again. But I don't really know.

**Comment by moeman2323** [comment]
One of my developers was able to resolve the issue. I can't provide details because this is outside my area of expertise, but he had to decompile the code for website and add a get max syntax to the Powerbi model to resolve it. I'll try to get details and post it.

**Comment by janicedawley** [comment]
Hi Mike --

If you do have some more information you can provide, I'd really appreciate it. We have some in-house developers who might be able to assist us if we know what needs to be fixed.

-- Janice

**Comment by janicedawley** [comment]
Thanks, Mike! Armed with that information, I was able to engage one of our in-house developers, who was also able to fix it. He did have to edit one other DLL to get it working, though -- the DisplayMonkey.Management.dll.  Ideally this would be fixed in the primary distribution of the code... but I'm not sure how the protocols work around that.

**Comment by psined1** [comment]
Hi, thanks everyone for contributing to find the solution to the issue. We'll have it added among other things to the next release shortly.

**Comment by rcashin** [comment]
Any more info on the changes you guys made before recompiling?

Any status on an update for the fix?

Thanks!

**Comment by psined1** [comment]
Planning to release fixes shortly. Please stay tuned. Thanks for your patience!
