### ISSUE TITLE
Expand PowerBI Report URL field length

### ISSUE THREAD

**Issue by tomblodget** [fuel9/DisplayMonkey#72]
We are running into an issue with some reports and not others. All are picked from the list in the Display Momkey PowerBI frame page. 

Looking at the source and database, there appears to be an arbitrary limitation on the PowerBI Report URL length (200). As a low-intensity db, a limit of `NVARCHAR(MAX)` seems better.

Symptom:

    Source | 
    Powerbi/Create
    
    Message | 
    The field Visualization URL must be a string or array type with a maximum length of '200'.
    
    Stack trace | 
    
    at DisplayMonkey.Models.DisplayMonkeyEntities.SaveChanges()
    at DisplayMonkey.Controllers.PowerbiController.Create(Powerbi powerbi)    
	at lambda_method(Closure , ControllerBase , Object[] )    
	at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)    
	at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)    
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()    
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by psined1** [comment]
Sounds like a duplicate for #70. I'm going to close this one. Already on the fix list.
